import {
  StepNode,
  SubStepNodeTop,
  SubStepNodeBottom,
  InvisibleNode,
  PhaseTitleNode,
  SubSubStepNodeBottom,
  NavNode,
} from './CustomNode';

export const initialNodes = [
  {
    id: 'phase-node-0',
    type: 'phase-node',
    position: { x: 0, y: -300 },
    data: {
      label: 'Identify Need',
      bgColor: '#545454',
      color: '#ffffff',
      widthScale: 1,
    },
  },
  {
    id: 'node-0',
    type: 'step-node',
    position: { x: 0, y: 0 },
    data: { label: 'IDN050', bgColor: '#545454', color: '#ffffff' },
  },
  {
    id: 'node-1',
    type: 'step-node',
    position: { x: 150, y: 0 },
    data: { label: 'IDN070', bgColor: '#545454', color: '#ffffff' },
  },

  {
    id: 'phase-node-1',
    type: 'phase-node',
    position: { x: 300, y: -300 },
    data: {
      label: 'Feasibility',
      bgColor: '#0cc0df',
      color: '#ffffff',
      widthScale: 1,
    },
  },
  {
    id: 'node-2',
    type: 'step-node',
    position: { x: 300, y: 0 },
    data: { label: 'FES030', bgColor: '#0cc0df', color: '#ffffff' },
  },
  {
    id: 'node-3',
    type: 'step-node',
    position: { x: 450, y: 0 },
    data: { label: 'FES070', bgColor: '#0cc0df', color: '#ffffff' },
  },

  {
    id: 'phase-node-2',
    type: 'phase-node',
    position: { x: 600, y: -300 },
    data: {
      label: 'Definition',
      bgColor: '#cb6ce6',
      color: '#ffffff',
      widthScale: 1,
    },
  },
  {
    id: 'node-4',
    type: 'step-node',
    position: { x: 600, y: 0 },
    data: { label: 'DEF030', bgColor: '#cb6ce6', color: '#ffffff' },
  },
  {
    id: 'node-5',
    type: 'step-node',
    position: { x: 750, y: 0 },
    data: { label: 'DEF050', bgColor: '#cb6ce6', color: '#ffffff' },
  },

  {
    id: 'phase-node-3',
    type: 'phase-node',
    position: { x: 900, y: -300 },
    data: {
      label: 'Delivery',
      bgColor: '#8c52ff',
      color: '#ffffff',
      widthScale: 1.7,
    },
  },
  {
    id: 'node-6',
    type: 'step-node',
    position: { x: 900, y: 0 },
    data: { label: 'DEL030', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-7',
    type: 'step-node',
    position: { x: 1050, y: 0 },
    data: { label: 'DEL060', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-8',
    type: 'step-node',
    position: { x: 1200, y: 0 },
    data: { label: 'DEL090', bgColor: '#8c52ff', color: '#ffffff' },
  },

  {
    id: 'phase-node-4',
    type: 'phase-node',
    position: { x: 1350, y: -300 },
    data: {
      label: 'Handover and Close',
      bgColor: '#0097b2',
      color: '#ffffff',
      widthScale: 1.7,
    },
  },
  {
    id: 'node-9',
    type: 'step-node',
    position: { x: 1350, y: 0 },
    data: { label: 'HOC020', bgColor: '#0097b2', color: '#ffffff' },
  },
  {
    id: 'node-10',
    type: 'step-node',
    position: { x: 1500, y: 0 },
    data: { label: 'HOC050', bgColor: '#0097b2', color: '#ffffff' },
  },
  {
    id: 'node-11',
    type: 'step-node',
    position: { x: 1650, y: 0 },
    data: { label: 'HOC070', bgColor: '#0097b2', color: '#ffffff' },
  },

  {
    id: 'phase-node-5',
    type: 'phase-node',
    position: { x: 1800, y: -300 },
    data: {
      label: 'Benefits',
      bgColor: '#5e17eb',
      color: '#ffffff',
      widthScale: 0.4,
    },
  },
  {
    id: 'node-12',
    type: 'step-node',
    position: { x: 1800, y: 0 },
    data: { label: 'BER020', bgColor: '#5e17eb', color: '#ffffff' },
  },
];

export const indvPhaseNodes = [
  {
    id: 'nav-node',
    type: 'nav-node',
    position: { x: 0, y: -550 },
    data: { label: '< Go Back' },
  },
  {
    id: 'phase-node-3',
    type: 'phase-node',
    position: { x: 0, y: -350 },
    data: {
      label: 'Delivery',
      bgColor: '#8c52ff',
      color: '#ffffff',
      widthScale: -1,
    },
  },

  {
    id: 'node-6.0',
    type: 'step-node',
    position: { x: 0, y: 0 },
    data: { label: 'DEL020', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.0.0',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: -65, y: 150 },
    data: {
      label: 'Detail design complete',
      bgColor: '#8c52ff',
      color: '#ffffff',
    },
  },

  {
    id: 'node-6.1',
    type: 'step-node',
    position: { x: 250, y: 0 },
    data: { label: 'DEL030', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.1.0',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 200, y: 150 },
    data: { label: 'Hazop assessment', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.1.1',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 200, y: 250 },
    data: { label: 'ALM assessment', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.1.2',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 200, y: 350 },
    data: { label: 'CPP checklist', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.1.3',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 180, y: 450 },
    data: {
      label: 'Has CS approved SoS?',
      bgColor: '#8c52ff',
      color: '#ffffff',
    },
  },
  {
    id: 'node-6.1.4',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 200, y: 550 },
    data: { label: 'Work Authorisation', bgColor: '#8c52ff', color: '#ffffff' },
  },

  {
    id: 'node-6.2',
    type: 'step-node',
    position: { x: 500, y: 0 },
    data: { label: 'DEL040', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.2.0',
    type: 'substep-node-top',
    sourcePosition: 'top',
    targetPosition: 'bottom',
    position: { x: 455, y: -120 },
    data: { label: 'Gateway 3 activity', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.2.1',
    type: 'substep-node-top',
    sourcePosition: 'top',
    targetPosition: 'bottom',
    position: { x: 455, y: -230 },
    data: { label: 'Gateway 3 outcome', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.2.2',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 420, y: 150 },
    data: {
      label: 'Construction delivery route',
      bgColor: '#8c52ff',
      color: '#ffffff',
    },
  },
  {
    id: 'node-6.2.3',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 420, y: 250 },
    data: {
      label: 'Construction contract status',
      bgColor: '#8c52ff',
      color: '#ffffff',
    },
  },
  {
    id: 'node-6.2.4',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 420, y: 350 },
    data: {
      label: 'Construction contractor',
      bgColor: '#8c52ff',
      color: '#ffffff',
    },
  },
  {
    id: 'node-6.2.5',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 440, y: 450 },
    data: {
      label: 'Has SoS actualised?',
      bgColor: '#8c52ff',
      color: '#ffffff',
    },
  },

  {
    id: 'node-6.3',
    type: 'step-node',
    position: { x: 750, y: 0 },
    data: {
      label: 'DEL060',
      color: '#8c52ff',
      bgColor: '#8c52ff',
      color: '#ffffff',
    },
  },
  {
    id: 'node-6.3.0',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 685, y: 150 },
    data: {
      label: 'Confidence in achieving PIU',
      bgColor: '#8c52ff',
      color: '#ffffff',
    },
  },
  {
    id: 'node-6.3.1',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 712, y: 250 },
    data: { label: 'Right first time', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.3.2',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 712, y: 350 },
    data: { label: 'Environment', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.3.3',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 712, y: 450 },
    data: { label: 'Safety', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.3.4',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 630, y: 550 },
    data: {
      label: 'Overall construction assessment',
      bgColor: '#8c52ff',
      color: '#ffffff',
    },
  },

  {
    id: 'node-6.4',
    type: 'step-node',
    position: { x: 1000, y: 0 },
    data: {
      label: 'DEL070',
      color: '#8c52ff',
      bgColor: '#8c52ff',
      color: '#ffffff',
    },
  },
  {
    id: 'node-6.4.0',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 950, y: 150 },
    data: {
      label: 'Overall I&A assessment',
      bgColor: '#8c52ff',
      color: '#ffffff',
    },
  },
  {
    id: 'node-6.4.0.0',
    type: 'subsubstep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 955, y: 220 },
    data: {
      label: 'DESAR - final submission',
      bgColor: '#8c52ff',
      color: '#ffffff',
    },
  },
  {
    id: 'node-6.4.0.1',
    type: 'subsubstep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 1000, y: 290 },
    data: { label: 'HAZZCOM', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.4.0.2',
    type: 'subsubstep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 975, y: 360 },
    data: { label: 'Training delivery', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.4.0.3',
    type: 'subsubstep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 995, y: 430 },
    data: { label: 'ALM', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-6.4.0.4',
    type: 'subsubstep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 995, y: 500 },
    data: { label: 'HAZOP', bgColor: '#8c52ff', color: '#ffffff' },
  },

  {
    id: 'node-6.5',
    type: 'step-node',
    position: { x: 1250, y: 0 },
    data: { label: 'DEL080', bgColor: '#8c52ff', color: '#ffffff' },
  },
  {
    id: 'node-inv',
    type: 'inv-node',
    position: { x: 1440, y: 21 },
    data: { label: '' },
  },
];

// we define the nodeTypes outside of the component to prevent re-renderings
// you could also use useMemo inside the component
export const nodeTypes = {
  'nav-node': NavNode,
  'phase-node': PhaseTitleNode,
  'step-node': StepNode,
  'substep-node-top': SubStepNodeTop,
  'substep-node-bottom': SubStepNodeBottom,
  'subsubstep-node-bottom': SubSubStepNodeBottom,
  'inv-node': InvisibleNode,
};
