import {
  StepNode,
  SubStepNodeTop,
  SubStepNodeBottom,
  LogoNode,
  SubSubStepNodeTop,
  InvisibleNode,
  PhaseTitleNode,
} from './CustomNode';

export const initialNodes = [
  {
    id: 'phase-node-0',
    type: 'phase-node',
    position: { x: 0, y: -300 },
    data: { label: 'Identify Need', color: '#545454' },
  },
  {
    id: 'node-0',
    type: 'step-node',
    position: { x: 0, y: 0 },
    data: { label: 'IDN050', color: '#545454' },
  },
  {
    id: 'node-1',
    type: 'step-node',
    position: { x: 150, y: 0 },
    data: { label: 'IDN070', color: '#545454' },
  },

  {
    id: 'phase-node-1',
    type: 'phase-node',
    position: { x: 300, y: -300 },
    data: { label: 'Feasibility', color: '#0cc0df' },
  },
  {
    id: 'node-2',
    type: 'step-node',
    position: { x: 300, y: 0 },
    data: { label: 'FES030', color: '#0cc0df' },
  },
  {
    id: 'node-3',
    type: 'step-node',
    position: { x: 450, y: 0 },
    data: { label: 'FES070', color: '#0cc0df' },
  },

  {
    id: 'phase-node-2',
    type: 'phase-node',
    position: { x: 600, y: -300 },
    data: { label: 'Definition', color: '#cb6ce6' },
  },
  {
    id: 'node-4',
    type: 'step-node',
    position: { x: 600, y: 0 },
    data: { label: 'DEF030', color: '#cb6ce6' },
  },
  {
    id: 'node-5',
    type: 'step-node',
    position: { x: 750, y: 0 },
    data: { label: 'DEF050', color: '#cb6ce6' },
  },

  {
    id: 'phase-node-3',
    type: 'phase-node',
    position: { x: 900, y: -300 },
    data: { label: 'Delivery', color: '#8c52ff', widthScale: 1.7 },
  },
  {
    id: 'node-6',
    type: 'step-node',
    position: { x: 900, y: 0 },
    data: { label: 'DEL030', color: '#8c52ff' },
  },
  {
    id: 'node-7',
    type: 'step-node',
    position: { x: 1050, y: 0 },
    data: { label: 'DEL060', color: '#8c52ff' },
  },
  {
    id: 'node-8',
    type: 'step-node',
    position: { x: 1200, y: 0 },
    data: { label: 'DEL090', color: '#8c52ff' },
  },

  {
    id: 'phase-node-4',
    type: 'phase-node',
    position: { x: 1350, y: -300 },
    data: { label: 'Handover and Close', color: '#0097b2', widthScale: 1.7 },
  },
  {
    id: 'node-9',
    type: 'step-node',
    position: { x: 1350, y: 0 },
    data: { label: 'HOC020', color: '#0097b2' },
  },
  {
    id: 'node-10',
    type: 'step-node',
    position: { x: 1500, y: 0 },
    data: { label: 'HOC050', color: '#0097b2' },
  },
  {
    id: 'node-11',
    type: 'step-node',
    position: { x: 1650, y: 0 },
    data: { label: 'HOC070', color: '#0097b2' },
  },

  {
    id: 'phase-node-5',
    type: 'phase-node',
    position: { x: 1800, y: -300 },
    data: { label: 'Benefits', color: '#5e17eb', widthScale: 0.4 },
  },
  {
    id: 'node-12',
    type: 'step-node',
    position: { x: 1800, y: 0 },
    data: { label: 'BER020', color: '#5e17eb' },
  },
];

export const indvPhaseNodes = [
  {
    id: 'phase-node-3',
    type: 'phase-node',
    position: { x: 0, y: -350 },
    data: { label: 'Delivery', color: '#8c52ff', widthScale: -1 },
  },

  {
    id: 'node-6.0',
    type: 'step-node',
    position: { x: 0, y: 0 },
    data: { label: 'DEL020', color: '#8c52ff' },
  },
  {
    id: 'node-6.0.0',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: -65, y: 150 },
    data: { label: 'Detail design complete' },
  },

  {
    id: 'node-6.1',
    type: 'step-node',
    position: { x: 250, y: 0 },
    data: { label: 'DEL030', color: '#8c52ff' },
  },
  {
    id: 'node-6.1.0',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 200, y: 150 },
    data: { label: 'Hazop assessment' },
  },
  {
    id: 'node-6.1.1',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 200, y: 250 },
    data: { label: 'ALM assessment' },
  },
  {
    id: 'node-6.1.2',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 200, y: 350 },
    data: { label: 'CPP checklist' },
  },
  {
    id: 'node-6.1.3',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 180, y: 450 },
    data: { label: 'Has CS approved SoS?' },
  },
  {
    id: 'node-6.1.4',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 200, y: 550 },
    data: { label: 'Work Authorisation' },
  },

  {
    id: 'node-6.2',
    type: 'step-node',
    position: { x: 500, y: 0 },
    data: { label: 'DEL040', color: '#8c52ff' },
  },
  {
    id: 'node-6.2.0',
    type: 'substep-node-top',
    sourcePosition: 'top',
    targetPosition: 'bottom',
    position: { x: 455, y: -120 },
    data: { label: 'Gateway 3 activity', color: '#8c52ff' },
  },
  {
    id: 'node-6.2.1',
    type: 'substep-node-top',
    sourcePosition: 'top',
    targetPosition: 'bottom',
    position: { x: 455, y: -230 },
    data: { label: 'Gateway 3 outcome', color: '#8c52ff' },
  },
  {
    id: 'node-6.2.2',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 420, y: 150 },
    data: { label: 'Construction delivery route' },
  },
  {
    id: 'node-6.2.3',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 420, y: 250 },
    data: { label: 'Construction contract status' },
  },
  {
    id: 'node-6.2.4',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 420, y: 350 },
    data: { label: 'Construction contractor' },
  },
  {
    id: 'node-6.2.5',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 440, y: 450 },
    data: { label: 'Has SoS actualised?' },
  },

  {
    id: 'node-6.3',
    type: 'step-node',
    position: { x: 750, y: 0 },
    data: { label: 'DEL060', color: '#8c52ff' },
  },
  {
    id: 'node-6.3.0',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 685, y: 150 },
    data: { label: 'Confidence in achieving PIU' },
  },
  {
    id: 'node-6.3.1',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 712, y: 250 },
    data: { label: 'Right first time' },
  },
  {
    id: 'node-6.3.2',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 712, y: 350 },
    data: { label: 'Environment' },
  },
  {
    id: 'node-6.3.3',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 712, y: 450 },
    data: { label: 'Safety' },
  },
  {
    id: 'node-6.3.4',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 680, y: 550 },
    data: { label: 'Overall construction assessment' },
  },

  {
    id: 'node-6.4',
    type: 'step-node',
    position: { x: 1000, y: 0 },
    data: { label: 'DEL070', color: '#8c52ff' },
  },
  {
    id: 'node-6.4.0',
    type: 'substep-node-bottom',
    sourcePosition: 'bottom',
    targetPosition: 'top',
    position: { x: 950, y: 150 },
    data: { label: 'Overall I&A assessment' },
  },

  {
    id: 'node-6.5',
    type: 'step-node',
    position: { x: 1250, y: 0 },
    data: { label: 'DEL080', color: '#8c52ff' },
  },
  {
    id: 'node-inv',
    type: 'inv-node',
    position: { x: 1440, y: 21 },
    data: { label: '' },
  },
  // {
  //   id: 'node-0',
  //   type: 'step-node',
  //   position: { x: 0, y: 0 },
  //   data: { label: 'node-0' },
  // },
  // {
  //   id: 'node-1',
  //   type: 'step-node',
  //   position: { x: 250, y: 0 },
  //   data: { label: 'node-1' },
  // },
  // {
  //   id: 'node-2',
  //   type: 'substep-node-top',
  //   sourcePosition: 'top',
  //   targetPosition: 'bottom',
  //   position: { x: 250, y: -100 },
  //   data: { label: 'node-2' },
  // },
  // {
  //   id: 'node-3',
  //   type: 'step-node',
  //   data: { label: 'node-3' },
  //   position: { x: 500, y: 0 },
  // },
  // {
  //   id: 'node-4',
  //   type: 'substep-node-top',
  //   // sourcePosition: 'top',
  //   // targetPosition: 'bottom',
  //   position: { x: 250, y: -200 },
  //   data: { label: 'node-4' },
  // },
  // {
  //   id: 'node-4.1',
  //   type: 'subsubstep-node',
  //   sourcePosition: 'top',
  //   targetPosition: 'bottom',
  //   position: { x: 120, y: -150 },
  //   data: { label: 'node-4.1' },
  // },
  // {
  //   id: 'node-4.2',
  //   type: 'subsubstep-node',
  //   sourcePosition: 'top',
  //   targetPosition: 'bottom',
  //   position: { x: 420, y: -150 },
  //   data: { label: 'node-4.2' },
  // },
  // {
  //   id: 'node-5',
  //   type: 'step-node',
  //   position: { x: 750, y: 0 },
  //   data: { label: 'node-5' },
  // },
  // {
  //   id: 'node-6',
  //   type: 'step-node',
  //   position: { x: 1000, y: 0 },
  //   data: { label: 'node-6' },
  // },
  // {
  //   id: 'node-7',
  //   type: 'step-node',
  //   position: { x: 1250, y: 0 },
  //   data: { label: 'node-7' },
  // },
  // {
  //   id: 'node-8',
  //   type: 'substep-node-bottom',
  //   sourcePosition: 'bottom',
  //   targetPosition: 'top',
  //   position: { x: 1000, y: 100 },
  //   data: { label: 'node-8' },
  // },
  // {
  //   id: 'node-9',
  //   type: 'substep-node-bottom',
  //   sourcePosition: 'bottom',
  //   targetPosition: 'top',
  //   position: { x: 1000, y: 200 },
  //   data: { label: 'node-9' },
  // },
  // {
  //   id: 'node-10',
  //   type: 'substep-node-top',
  //   sourcePosition: 'top',
  //   targetPosition: 'bottom',
  //   position: { x: 1250, y: -100 },
  //   data: { label: 'node-10' },
  // },
  // {
  //   id: 'node-10.1',
  //   type: 'subsubstep-node',
  //   sourcePosition: 'top',
  //   targetPosition: 'bottom',
  //   position: { x: 1150, y: -180 },
  //   data: { label: 'node-10.1' },
  // },
  // {
  //   id: 'node-11',
  //   type: 'inv-node',
  //   position: { x: 1440, y: 21 },
  //   data: { label: 'node-11' },
  // },
];
// we define the nodeTypes outside of the component to prevent re-renderings
// you could also use useMemo inside the component
export const nodeTypes = {
  'phase-node': PhaseTitleNode,
  'step-node': StepNode,
  'substep-node-top': SubStepNodeTop,
  'substep-node-bottom': SubStepNodeBottom,
  'subsubstep-node': SubSubStepNodeTop,
  'inv-node': InvisibleNode,
};
